module.exports = {
  skills: {
    'Front-End :': ' HTML5, CSS3, Bootstrap, Foundation, Javascript, Angular, ReactJS',
    'Mobile :': 'iOS, Android',
    'Back-End :': 'WordPress, Drupal, Node.js, GraphQL, MongoDB',
    'Workflow :': ' Gulp.js / Grunt.js / Webpack',
    'Autres :': 'Python, GoLang, Git, Redmine, Jira, Adobe, Photoshop, Invision, Zeplin, npm, yarn',
    'Méthodes :': ' Agile Scrum, ...',
    'Secteurs Métiers:': ' Assurances, Tourisme, Banque ...'
  },
  status: 'Consultant Etudes & Développement [Web /Mobile/ et/ou Techno principale]',
  languages: ['Français', 'Anglais', 'Arabe'],
  experience: 2,
  firstName: 'Fake',
  lastName: 'News',
  educations: { '2018 :': 'Autre ...', '2015 :': 'Master ...', '2010 :': 'Bac ...' },
  LANGUAGE: 'language',
  LANGUAGE_LVL: 'langLvl',
  ED_DETAILS: 'edDetails',
  EDUCATION: 'education',
  SKILL_DETAILS: 'skillDetails',
  SKILLS: 'skills',
  EXPERIANCE: 'experiance',
  ENTREPRISE: 'entreprise',
  FONCTION: 'fonction',
  MISSION: 'mission',
  DESCRIPTION_MISSION: 'description',
  TACHE_MISSION: 'tache',
  ENV_TECHNIQUE: 'environnement_technique'
}
